name: Polis
version: '${project.version}'
main: com.gylderia.polis.Polis
api-version: '1.20'
commands:
  townCreate:
    description: Create a town
    usage: /townCreate <name>
  debugcache:
    description: Debug cache
    usage: /debugcache
  jointown:
    description: Join a town
    usage: /joinTown <name>
  towninvite:
    description: Invite a player to your town
    usage: /towninvite <name>
